version: '3.8'

services:
  # Backend Service
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - LOG_LEVEL=info
      - WEBSOCKET_PORT=8001
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis

  # Frontend Service
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8001
    depends_on:
      - backend

  # Redis for pub/sub and message queue
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Log Agent (optional, can be run on remote servers)
  log-agent:
    build: ./agent
    volumes:
      - ./agent:/app
      # Mount the log directory you want to monitor
      # - /var/log/nginx:/logs:ro
    environment:
      - LOG_FILE=/app/example.log
      - SERVER_URL=backend:8000
    depends_on:
      - backend

volumes:
  redis_data:
